let
    Source = Json.Document(Web.Contents("https://api.msrc.microsoft.com/sug/v2.0/en-US/vulnerability" & "?%24orderBy=cveNumber+desc&%24filter=%28releaseDate+gt+" & #"Vulnerability Start" & "T00%3A00%3A00-05%3A00+or+latestRevisionDate+gt+" & #"Vulnerability Start" & "T00%3A00%3A00-05%3A00%29+and+%28releaseDate+lt+" & #"Vulnerability End" & "T23%3A59%3A59-05%3A00+or+latestRevisionDate+lt+" & #"Vulnerability End" & "T23%3A59%3A59-05%3A00%29")),
    #"Converted to Table" = Table.FromRecords({Source}),
    #"Expanded value" = Table.ExpandListColumn(#"Converted to Table", "value"),
    #"Expanded value1" = Table.ExpandRecordColumn(#"Expanded value", "value", {"id", "releaseDate", "cveNumber", "cveTitle", "releaseNumber", "vulnType", "latestRevisionDate", "description", "unformattedDescription", "mitreText", "mitreUrl", "publiclyDisclosed", "exploited", "latestSoftwareReleaseId", "latestSoftwareRelease", "olderSoftwareReleaseId", "olderSoftwareRelease", "denialOfService", "tag", "issuingCna", "severityId", "severity", "impactId", "impact", "langCode", "baseScore", "temporalScore", "vectorString", "isMariner", "articles", "revisions"}, {"value.id", "value.releaseDate", "value.cveNumber", "value.cveTitle", "value.releaseNumber", "value.vulnType", "value.latestRevisionDate", "value.description", "value.unformattedDescription", "value.mitreText", "value.mitreUrl", "value.publiclyDisclosed", "value.exploited", "value.latestSoftwareReleaseId", "value.latestSoftwareRelease", "value.olderSoftwareReleaseId", "value.olderSoftwareRelease", "value.denialOfService", "value.tag", "value.issuingCna", "value.severityId", "value.severity", "value.impactId", "value.impact", "value.langCode", "value.baseScore", "value.temporalScore", "value.vectorString", "value.isMariner", "value.articles", "value.revisions"}),
    #"Changed Type" = Table.TransformColumnTypes(#"Expanded value1",{{"@odata.context", type text}, {"@odata.count", Int64.Type}, {"value.id", type text}, {"value.releaseDate", type text}, {"value.cveNumber", type text}, {"value.cveTitle", type text}, {"value.releaseNumber", type date}, {"value.vulnType", type text}, {"value.latestRevisionDate", type datetime}, {"value.description", type any}, {"value.unformattedDescription", type any}, {"value.mitreText", type text}, {"value.mitreUrl", type text}, {"value.publiclyDisclosed", type text}, {"value.exploited", type text}, {"value.latestSoftwareReleaseId", Int64.Type}, {"value.latestSoftwareRelease", type text}, {"value.olderSoftwareReleaseId", Int64.Type}, {"value.olderSoftwareRelease", type text}, {"value.denialOfService", type text}, {"value.tag", type text}, {"value.issuingCna", type text}, {"value.severityId", Int64.Type}, {"value.severity", type text}, {"value.impactId", Int64.Type}, {"value.impact", type text}, {"value.langCode", type text}, {"value.baseScore", type number}, {"value.temporalScore", type number}, {"value.vectorString", type text}, {"value.isMariner", type logical}, {"value.articles", type any}, {"value.revisions", type any}}),
    #"Replaced Value" = Table.ReplaceValue(#"Changed Type","T07:00:00Z","",Replacer.ReplaceText,{"value.releaseDate"}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Replaced Value",{{"value.releaseNumber", type text}, {"value.latestRevisionDate", type text}}),
    #"Replaced Value1" = Table.ReplaceValue(#"Changed Type1"," 2:00:00 AM","",Replacer.ReplaceText,{"value.latestRevisionDate"}),
    #"Removed Columns" = Table.RemoveColumns(#"Replaced Value1",{"value.description", "value.unformattedDescription", "value.olderSoftwareReleaseId", "value.olderSoftwareRelease", "value.severityId", "value.impactId", "value.langCode", "value.isMariner", "value.articles", "value.revisions", "value.latestSoftwareReleaseId"}),
    #"Split Column by Delimiter" = Table.SplitColumn(#"Removed Columns", "value.vectorString", Splitter.SplitTextByDelimiter("/", QuoteStyle.Csv), {"value.vectorString.1", "value.vectorString.2", "value.vectorString.3", "value.vectorString.4", "value.vectorString.5", "value.vectorString.6", "value.vectorString.7", "value.vectorString.8", "value.vectorString.9", "value.vectorString.10", "value.vectorString.11", "value.vectorString.12"}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"value.vectorString.1", type text}, {"value.vectorString.2", type text}, {"value.vectorString.3", type text}, {"value.vectorString.4", type text}, {"value.vectorString.5", type text}, {"value.vectorString.6", type text}, {"value.vectorString.7", type text}, {"value.vectorString.8", type text}, {"value.vectorString.9", type text}, {"value.vectorString.10", type text}, {"value.vectorString.11", type text}, {"value.vectorString.12", type text}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type2",{{"value.vectorString.2", "Attack Vector"}, {"value.vectorString.5", "User Interaction"}}),
    #"Replaced Value2" = Table.ReplaceValue(#"Renamed Columns","AV:N","Network",Replacer.ReplaceText,{"Attack Vector"}),
    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","AV:L","Local",Replacer.ReplaceText,{"Attack Vector"}),
    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","AV:A","Adjacent",Replacer.ReplaceText,{"Attack Vector"}),
    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","AV:P","Physical",Replacer.ReplaceText,{"Attack Vector"}),
    #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5","UI:R","Required",Replacer.ReplaceText,{"User Interaction"}),
    #"Replaced Value7" = Table.ReplaceValue(#"Replaced Value6","UI:N","None",Replacer.ReplaceText,{"User Interaction"}),
    #"Removed Columns1" = Table.RemoveColumns(#"Replaced Value7",{"value.vectorString.3", "value.vectorString.4", "value.vectorString.6", "value.vectorString.7", "value.vectorString.8", "value.vectorString.9", "value.vectorString.10", "value.vectorString.11", "value.vectorString.12", "value.vectorString.1"}),
    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns1",{{"value.latestRevisionDate", "Latest Release"}, {"value.cveTitle", "Title"}, {"value.cveNumber", "CVE"}, {"value.mitreUrl", "URL"}, {"value.publiclyDisclosed", "Publicly Disclosed"}, {"value.exploited", "Exploited"}, {"value.latestSoftwareRelease", "Exploitation"}, {"value.denialOfService", "Denial Of Service"}, {"value.tag", "Tag"}, {"value.issuingCna", "Issuing CNA"}, {"value.severity", "Severity"}, {"value.impact", "Impact"}, {"value.temporalScore", "CVSS Score"}, {"value.baseScore", "Base Score"}})
in
    #"Renamed Columns1"